import { NextRequest, NextResponse } from "next/server";

const API_KEY = process.env.RAPIDAPI_KEY || "";
const HOST = "trade-bloom-finance.p.rapidapi.com";

async function bloomGet(path: string) {
  try {
    const res = await fetch(`https://${HOST}${path}`, {
      headers: {
        "Content-Type": "application/json",
        "x-rapidapi-key": API_KEY,
        "x-rapidapi-host": HOST,
      },
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) return null;
    return res.json();
  } catch { return null; }
}

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl;
  const type = searchParams.get("type");

  if (!API_KEY) return NextResponse.json({ error: "API key missing" }, { status: 500 });

  try {
    switch (type) {
      // ── Bloomberg News Feed ──
      case "news": {
        const [newsData, topData] = await Promise.all([
          bloomGet("/news/list"),
          bloomGet("/news/top-news"),
        ]);
        const articles: any[] = [];
        // Extract from /news/list
        if (newsData?.data?.modules) {
          for (const mod of newsData.data.modules) {
            if (mod.stories) {
              for (const s of mod.stories) {
                articles.push({
                  id: s.id || s.internalID,
                  title: s.title,
                  summary: s.autoGeneratedSummary || s.summary || "",
                  category: s.primaryCategory || s.label || s.eyebrowSite || "",
                  site: s.primarySite || "",
                  author: s.byline || "",
                  published: s.published ? new Date(s.published * 1000).toISOString() : "",
                  url: s.shortURL || s.longURL || "",
                  isPremium: !!s.premium,
                  wordCount: s.wordCount || 0,
                  duration: s.duration || null,
                  type: s.type || "article",
                });
              }
            }
          }
        }
        // Index bar from top-news
        let indexBar: any[] = [];
        if (topData?.data?.indexBar?.quotes) {
          indexBar = Object.values(topData.data.indexBar.quotes).map((q: any) => ({
            name: q.tinyName || q.name,
            symbol: q.symbol,
            last: q.last,
            netChange: q.netChange,
            pctChange: q.pctChange,
            dayHigh: q.dayHigh,
            dayLow: q.dayLow,
            yearHigh: q.yearHigh,
            yearLow: q.yearLow,
            volume: q.volume,
          }));
        }
        return NextResponse.json({ articles, indexBar });
      }

      // ── DOW JONES Market Movers ──
      case "movers": {
        const data = await bloomGet("/markets/movers?query=indu:ind");
        if (!data?.data) return NextResponse.json({ movers: [], active: [] });
        const movers = data.data.mostActive || data.data.active || [];
        const gainers = data.data.gainers || [];
        const losers = data.data.losers || [];
        const mapMover = (m: any) => ({
          symbol: m.symbol,
          name: m.tinyName || m.name,
          last: parseFloat(m.last || "0"),
          netChange: parseFloat(m.netChange || "0"),
          pctChange: parseFloat(m.pctChange || "0"),
          volume: m.volume ? parseFloat(String(m.volume)) : 0,
          dayHigh: parseFloat(m.dayHigh || "0"),
          dayLow: parseFloat(m.dayLow || "0"),
          yearHigh: parseFloat(m.yearHigh || "0"),
          yearLow: parseFloat(m.yearLow || "0"),
          exchange: m.exchange || "",
        });
        return NextResponse.json({
          active: movers.map(mapMover),
          gainers: gainers.map(mapMover),
          losers: losers.map(mapMover),
        });
      }

      // ── Commodities (Gold, Oil, Silver, etc.) ──
      case "commodities": {
        const data = await bloomGet(
          "/markets/compact?ids=gc1%2Ccl1%2Csi1%2Cho1%2Cng1%2Cco1%2Ckc1%2Cct1%2Csb1%2Cw%201%2Cc%201%2Cs%201%2Cxb1%2Crs1%2Crr1%2Ccp1%2Cqs1%2Cjo1%2Csm1%2Cfc1%2Cdl1%2Cjg1%2Cji1%2Cjn1%2Cjx1%2Clc1%2Clh1%2Cxaueur%3Acur%2Cxaugbp%3Acur%2Cxagusd%3Acur%2Cxagjpy%3Acur%2Cxageur%3Acur%2Cxaginr%3Acur%2Cxpt%3Acur%2Cxpd%3Acur"
        );
        if (!data?.data) return NextResponse.json({ commodities: [] });
        const commodities = Object.entries(data.data).map(([id, d]: [string, any]) => ({
          id,
          symbol: d.symbol || id,
          name: d.tinyName || d.name || id,
          last: parseFloat(d.last || "0"),
          netChange: parseFloat(d.netChange || "0"),
          pctChange: parseFloat(d.pctChange || "0"),
          dayHigh: parseFloat(d.dayHigh || "0"),
          dayLow: parseFloat(d.dayLow || "0"),
          currency: d.currency || "USD",
          unit: d.unit || "",
        }));
        return NextResponse.json({ commodities });
      }

      // ── Cross Currencies ──
      case "currencies": {
        const data = await bloomGet(
          "/markets/scross-currencies?id=eur%2Cgbp%2Cjpy%2Cusd%2Cchf%2Caud%2Ccad%2Cnzd%2Ccny%2Ccnh%2Cinr%2Ckrw%2Cmxn%2Cbrl%2Csgd%2Chkd%2Csek%2Cnok%2Cdkk%2Czar%2Ctry%2Cthb%2Cphp%2Cidr%2Cmyr%2Ctwd%2Cczk%2Cpln%2Chuf%2Cils%2Crub%2Caed%2Ccop"
        );
        if (!data?.data) return NextResponse.json({ currencies: [] });
        const currencies = Object.entries(data.data)
          .filter(([, d]: [string, any]) => {
            // Only keep major pairs vs USD
            const sym = (d.symbol || "").toUpperCase();
            return sym.endsWith("USD") || sym.startsWith("USD");
          })
          .map(([id, d]: [string, any]) => ({
            id,
            symbol: d.symbol,
            name: d.tinyName || d.name || id,
            last: parseFloat(d.last || "0"),
            netChange: parseFloat(d.netChange || "0"),
            pctChange: parseFloat(d.pctChange || "0"),
            dayHigh: parseFloat(d.dayHigh || "0"),
            dayLow: parseFloat(d.dayLow || "0"),
            yearHigh: parseFloat(d.yearHigh || "0"),
            yearLow: parseFloat(d.yearLow || "0"),
          }));
        return NextResponse.json({ currencies });
      }

      // ── Stock Key Stats ──
      case "key-stats": {
        const ticker = searchParams.get("ticker");
        if (!ticker) return NextResponse.json({ error: "ticker required" }, { status: 400 });
        const data = await bloomGet(`/stocks/key-stats?query=${encodeURIComponent(ticker)}`);
        return NextResponse.json(data?.data || {});
      }

      // ── Stock Financials ──
      case "financials": {
        const ticker = searchParams.get("ticker");
        if (!ticker) return NextResponse.json({ error: "ticker required" }, { status: 400 });
        const data = await bloomGet(`/stocks/financials?query=${encodeURIComponent(ticker)}`);
        return NextResponse.json(data?.data || {});
      }

      // ── Auto-complete ──
      case "search": {
        const q = searchParams.get("q");
        if (!q) return NextResponse.json({ results: [] });
        const data = await bloomGet(`/auto-complete?query=${encodeURIComponent(q)}`);
        const results = data?.data?.quote || [];
        return NextResponse.json({
          results: results.map((r: any) => ({
            symbol: r.symbol,
            name: r.tinyName || r.name,
            exchange: r.exchange || "",
            ticker: r.ticker,
            resourceId: r.resourceId,
            country: r.country || "",
          })),
        });
      }

      default:
        return NextResponse.json({ error: "Invalid type. Use: news|movers|commodities|currencies|key-stats|financials|search" }, { status: 400 });
    }
  } catch (err) {
    console.error("Bloomberg API error:", err);
    return NextResponse.json({ error: "Failed to fetch" }, { status: 500 });
  }
}